branch-defaults:
  default:
    environment: udagram-api3-dev
    group_suffix: null
global:
  application_name: udagram-api3
  branch: null
  default_ec2_keyname: udagram
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023/6.0.3
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
